AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-api

  Sample SAM Template for orders-api

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java11
    Tracing: Active
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable
  Api:
    TracingEnabled: True

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders-api
      Handler: net.ontopsolutions.api.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  ReadOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders-api
      Handler: net.ontopsolutions.api.ReadOrdersLambda::getOrders
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET

Outputs:
  CreateOrdersAPI:
    Description: "API Gateway endpoint to create orders function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazon.com/Prod/orders"
  CreateOrderFunction:
    Description: "Create order Lambda Function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole:
    Description: "Create order Lambda Function Im role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn
